name: Daily Coze Update

on:
  schedule:
    - cron: '0 1 * * *'  # 北京时间 15:45 (UTC+8 07:45)
  workflow_dispatch:      # 允许手动触发

jobs:
  update-coze:
    runs-on: ubuntu-latest
    steps:
      - name: Call Coze API
        run: |
          DATE=$(date +%Y%m)
          curl -X POST "https://api.coze.cn/v1/workflow/run" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer pat_gcqyJlPUruKgr4ekZ6XI8mf0wHqsmdXE0uKW8YsXv8jhKmho5ZKiJNqvcjhE4JnC" \
          -d "{\"workflow_id\": \"7480889381671174155\", \"parameters\": {\"date\": \"$DATE\"}}"
