name: Daily Coze Update

on:
  schedule:
    - cron: '37 15 * * *'  # 每天 UTC 00:00 执行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-coze:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API endpoint
        run: |
          curl -X POST "https://api.coze.cn/v1/workflow/run" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer pat_Z3QBeLnkotW0vUfXLfGgtd7v25sKErqC7oBHEBKy9zEAG6UCGyG1IOPX6SGyKOLD" \
          -d '{
            "workflow_id": "7480889381671174155",
            "parameters": {
              "date": "'$(date +%Y%m')'"
            }
          }'
